"""Grover: The agentic filesystem.

Safe file operations, knowledge graphs, and semantic search — unified for AI agents.
"""

__version__ = "0.0.4"

from grover.backends.user_scoped import UserScopedFileSystem
from grover.client import Grover, GroverAsync
from grover.mount import Mount
from grover.providers import (
    ChunkProvider,
    DefaultChunkProvider,
    DefaultVersionProvider,
    DiskStorageProvider,
    EmbeddingProvider,
    GraphProvider,
    SearchProvider,
    StorageProvider,
    VersionProvider,
)
from grover.providers.graph.types import SubgraphResult
from grover.providers.search.filters import (
    FilterExpression,
    FilterValue,
    and_,
    eq,
    exists,
    gt,
    gte,
    in_,
    lt,
    lte,
    ne,
    not_in,
    or_,
)
from grover.providers.search.protocol import (
    SupportsHybridSearch,
    SupportsIndexLifecycle,
    SupportsMetadataFilter,
    SupportsNamespaces,
    SupportsReranking,
)
from grover.providers.search.types import (
    DeleteResult as SearchDeleteResult,
)
from grover.providers.search.types import (
    IndexConfig,
    IndexInfo,
    SearchResult,
    UpsertResult,
    VectorEntry,
)
from grover.ref import Ref
from grover.results import (
    AncestorsResult,
    BetweennessResult,
    ChunkListResult,
    ChunkResult,
    ClosenessResult,
    CommonNeighborsResult,
    ConnectionCandidate,
    ConnectionListResult,
    ConnectionResult,
    DegreeResult,
    DeleteResult,
    DescendantsResult,
    DiffVersionsResult,
    EditResult,
    EgoGraphResult,
    Evidence,
    ExistsResult,
    FileCandidate,
    FileInfoResult,
    FileOperationResult,
    FileSearchResult,
    GetVersionContentResult,
    GlobEvidence,
    GlobResult,
    GraphEvidence,
    GraphResult,
    GrepEvidence,
    GrepResult,
    HarmonicResult,
    HasPathResult,
    HitsResult,
    HybridSearchResult,
    KatzResult,
    LexicalSearchResult,
    LineMatch,
    ListDirResult,
    MeetingSubgraphResult,
    MkdirResult,
    MoveResult,
    PageRankResult,
    PredecessorsResult,
    ReadResult,
    ReconcileResult,
    RestoreResult,
    ShareResult,
    ShareSearchResult,
    ShortestPathResult,
    SubgraphSearchResult,
    SuccessorsResult,
    TrashResult,
    TreeResult,
    VectorEvidence,
    VectorSearchResult,
    VerifyVersionResult,
    VersionChainError,
    VersionResult,
    WriteResult,
)
from grover.worker import IndexingMode

__all__ = [
    "AncestorsResult",
    "BetweennessResult",
    "ChunkListResult",
    "ChunkProvider",
    "ChunkResult",
    "ClosenessResult",
    "CommonNeighborsResult",
    "ConnectionCandidate",
    "ConnectionListResult",
    "ConnectionResult",
    "DefaultChunkProvider",
    "DefaultVersionProvider",
    "DegreeResult",
    "DeleteResult",
    "DescendantsResult",
    "DiffVersionsResult",
    "DiskStorageProvider",
    "EditResult",
    "EgoGraphResult",
    "EmbeddingProvider",
    "Evidence",
    "ExistsResult",
    "FileCandidate",
    "FileInfoResult",
    "FileOperationResult",
    "FileSearchResult",
    "FilterExpression",
    "FilterValue",
    "GetVersionContentResult",
    "GlobEvidence",
    "GlobResult",
    "GraphEvidence",
    "GraphProvider",
    "GraphResult",
    "GrepEvidence",
    "GrepResult",
    "Grover",
    "GroverAsync",
    "HarmonicResult",
    "HasPathResult",
    "HitsResult",
    "HybridSearchResult",
    "IndexConfig",
    "IndexInfo",
    "IndexingMode",
    "KatzResult",
    "LexicalSearchResult",
    "LineMatch",
    "ListDirResult",
    "MeetingSubgraphResult",
    "MkdirResult",
    "Mount",
    "MoveResult",
    "PageRankResult",
    "PredecessorsResult",
    "ReadResult",
    "ReconcileResult",
    "Ref",
    "RestoreResult",
    "SearchDeleteResult",
    "SearchProvider",
    "SearchResult",
    "ShareResult",
    "ShareSearchResult",
    "ShortestPathResult",
    "StorageProvider",
    "SubgraphResult",
    "SubgraphSearchResult",
    "SuccessorsResult",
    "SupportsHybridSearch",
    "SupportsIndexLifecycle",
    "SupportsMetadataFilter",
    "SupportsNamespaces",
    "SupportsReranking",
    "TrashResult",
    "TreeResult",
    "UpsertResult",
    "UserScopedFileSystem",
    "VectorEntry",
    "VectorEvidence",
    "VectorSearchResult",
    "VerifyVersionResult",
    "VersionChainError",
    "VersionProvider",
    "VersionResult",
    "WriteResult",
    "__version__",
    "and_",
    "eq",
    "exists",
    "gt",
    "gte",
    "in_",
    "lt",
    "lte",
    "ne",
    "not_in",
    "or_",
]
