"""Grover: The agentic filesystem.

Safe file operations, knowledge graphs, and semantic search — unified for AI agents.
"""

__version__ = "0.0.3"

from grover._grover import Grover
from grover._grover_async import GroverAsync
from grover.fs.user_scoped_fs import UserScopedFileSystem
from grover.graph.protocols import GraphStore
from grover.graph.types import SubgraphResult
from grover.mount import Mount, ProtocolConflictError, ProtocolNotAvailableError
from grover.ref import Ref, file_ref
from grover.search._engine import SearchEngine
from grover.search.filters import (
    FilterExpression,
    and_,
    eq,
    exists,
    gt,
    gte,
    in_,
    lt,
    lte,
    ne,
    not_in,
    or_,
)
from grover.search.protocols import (
    EmbeddingProvider,
    SupportsHybridSearch,
    SupportsIndexLifecycle,
    SupportsMetadataFilter,
    SupportsNamespaces,
    SupportsReranking,
    SupportsTextIngest,
    SupportsTextSearch,
    VectorStore,
)
from grover.search.types import (
    DeleteResult as SearchDeleteResult,
)
from grover.search.types import (
    IndexConfig,
    IndexInfo,
    SearchResult,
    UpsertResult,
    VectorEntry,
)
from grover.types import (
    ConnectionResult,
    DeleteResult,
    EditResult,
    Evidence,
    FileInfoResult,
    FileOperationResult,
    FileSearchCandidate,
    FileSearchResult,
    GetVersionContentResult,
    GlobEvidence,
    GlobResult,
    GraphEvidence,
    GraphResult,
    GrepEvidence,
    GrepResult,
    HybridSearchResult,
    LexicalSearchResult,
    LineMatch,
    ListDirResult,
    MkdirResult,
    MoveResult,
    ReadResult,
    RestoreResult,
    ShareResult,
    ShareSearchResult,
    TrashResult,
    TreeResult,
    VectorEvidence,
    VectorSearchResult,
    VersionResult,
    WriteResult,
)

__all__ = [
    "ConnectionResult",
    "DeleteResult",
    "EditResult",
    "EmbeddingProvider",
    "Evidence",
    "FileInfoResult",
    "FileOperationResult",
    "FileSearchCandidate",
    "FileSearchResult",
    "FilterExpression",
    "GetVersionContentResult",
    "GlobEvidence",
    "GlobResult",
    "GraphEvidence",
    "GraphResult",
    "GraphStore",
    "GrepEvidence",
    "GrepResult",
    "Grover",
    "GroverAsync",
    "HybridSearchResult",
    "IndexConfig",
    "IndexInfo",
    "LexicalSearchResult",
    "LineMatch",
    "ListDirResult",
    "MkdirResult",
    "Mount",
    "MoveResult",
    "ProtocolConflictError",
    "ProtocolNotAvailableError",
    "ReadResult",
    "Ref",
    "RestoreResult",
    "SearchDeleteResult",
    "SearchEngine",
    "SearchResult",
    "ShareResult",
    "ShareSearchResult",
    "SubgraphResult",
    "SupportsHybridSearch",
    "SupportsIndexLifecycle",
    "SupportsMetadataFilter",
    "SupportsNamespaces",
    "SupportsReranking",
    "SupportsTextIngest",
    "SupportsTextSearch",
    "TrashResult",
    "TreeResult",
    "UpsertResult",
    "UserScopedFileSystem",
    "VectorEntry",
    "VectorEvidence",
    "VectorSearchResult",
    "VectorStore",
    "VersionResult",
    "WriteResult",
    "__version__",
    "and_",
    "eq",
    "exists",
    "file_ref",
    "gt",
    "gte",
    "in_",
    "lt",
    "lte",
    "ne",
    "not_in",
    "or_",
]
