"""Generate the Rust tokenizer's Unicode tables from this interpreter.

The Rust tokenizer must be byte-identical to ``vfs.models.lexical``'s
pure tokenizer, whose character classes are Python's own (``re``'s
``\\w``, ``str.isupper``, ``str.islower``, ``str.isdigit``,
``str.casefold``). Rather than trust a third-party Unicode crate to
agree with CPython's tables, the classes are dumped from the interpreter
as range tables and a casefold map, so the Rust side is exact by
construction for this interpreter's Unicode version; the assigned set
lets the parity suite tell a Unicode-version drift from a bug.

    uv run --no-sync python scripts/gen_unicode_tables.py

Rewrites ``crates/vfs-core/src/lexical_tables.rs``; rebuild the engine
afterwards (``uv sync --reinstall-package vfs-py``).
"""

from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable

TARGET = Path(__file__).resolve().parent.parent / "crates" / "vfs-core" / "src" / "lexical_tables.rs"

_WORD = re.compile(r"\w")
_SURROGATES = range(0xD800, 0xE000)


def code_points() -> Iterable[int]:
    """Every code point a ``str`` can hold, in order."""
    return (cp for cp in range(0x110000) if cp not in _SURROGATES)


def ranges(predicate: Callable[[str], bool]) -> list[tuple[int, int]]:
    """Maximal runs of code points satisfying *predicate* (surrogates never do)."""
    out: list[tuple[int, int]] = []
    start: int | None = None
    previous = -2
    for cp in code_points():
        hit = predicate(chr(cp))
        if hit and (start is None or cp != previous + 1):
            if start is not None:
                out.append((start, previous))
            start = cp
        elif not hit and start is not None:
            out.append((start, previous))
            start = None
        if hit:
            previous = cp
    if start is not None:
        out.append((start, previous))
    return out


def casefolds() -> list[tuple[int, str]]:
    """Every code point whose ``casefold`` differs from itself, with the fold."""
    return [(cp, chr(cp).casefold()) for cp in code_points() if chr(cp).casefold() != chr(cp)]


def render() -> str:
    lines = [
        f"//! Generated by scripts/gen_unicode_tables.py from CPython {sys.version.split()[0]},",
        f"//! Unicode {unicodedata.unidata_version}. Do not edit: these are the interpreter's own",
        "//! character classes, so the Rust tokenizer cannot disagree with the pure one.",
        "",
        f'pub const PYTHON_VERSION: &str = "{sys.version.split()[0]}";',
        f'pub const UNICODE_VERSION: &str = "{unicodedata.unidata_version}";',
        "",
    ]
    tables = {
        "WORD": lambda ch: _WORD.fullmatch(ch) is not None,
        "UPPER": str.isupper,
        "LOWER": str.islower,
        "DIGIT": str.isdigit,
        "ASSIGNED": lambda ch: unicodedata.category(ch) != "Cn",
    }
    for name, predicate in tables.items():
        rs = ranges(predicate)
        lines.append(f"pub static {name}: [(u32, u32); {len(rs)}] = [")
        lines.extend(f"    (0x{lo:X}, 0x{hi:X})," for lo, hi in rs)
        lines.append("];")
        lines.append("")
    folds = casefolds()
    lines.append(f"pub static CASEFOLD: [(u32, &str); {len(folds)}] = [")
    for cp, folded in folds:
        literal = "".join(f"\\u{{{ord(c):X}}}" for c in folded)
        lines.append(f'    (0x{cp:X}, "{literal}"),')
    lines.append("];")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    TARGET.write_text(render())
    sys.stdout.write(f"wrote {TARGET}\n")
