"""Interface of the compiled Rust engine module (crates/vfs-core, pyo3).

The implementation lives in crates/vfs-core/src/python.rs; this stub is
the typed surface the seam (vfs/native.py) programs against.
"""

from collections.abc import Sequence

PROTOCOL_VERSION: int
LEXICAL_UNICODE_VERSION: str
LEXICAL_PYTHON_VERSION: str

def distinct_gram_count(data: bytes, cap: int) -> int: ...
def supported_grammars() -> list[str]: ...
def chunk_spans(
    bodies: list[tuple[bytes, str]], *, chunk_size: int
) -> list[list[tuple[int, int, int, int, bool]] | None]: ...
def tokenize(content: str) -> list[str]: ...
def lexical_char_classes() -> bytes: ...
def lexical_casefolds() -> list[tuple[int, str]]: ...
def lexical_score(
    blocks: Sequence[tuple[int, float, bytes, bytes, bytes]],
    idfs: Sequence[float],
    avg_dl: float,
    k: int,
    candidates: bytes | None = None,
) -> list[tuple[int, float]]: ...

class PostingsBuilder:
    def add_docs(self, docs: list[tuple[int, bytes]]) -> None: ...
    def next_batch(self, byte_cap: int) -> list[tuple[int, bytes, int]] | None: ...

class LexicalBuilder:
    def add_docs(self, docs: list[tuple[int, str]]) -> list[int]: ...
    def finish(self) -> tuple[int, float]: ...
    def next_df_batch(self, row_cap: int) -> list[tuple[str, int, float, float, bytes]] | None: ...
    def next_batch(self, row_cap: int) -> list[tuple[str, int, int, bytes, bytes, bytes]] | None: ...

class ContentMatcher:
    def __init__(self, pattern: str, case_insensitive: bool) -> None: ...
    def count_lines(
        self, bodies: list[bytes], *, cap: int | None, invert: bool, budget: float | None
    ) -> tuple[list[int], bool]: ...
    def hit_lines(
        self, bodies: list[bytes], *, before: int, after: int, cap: int | None, invert: bool, budget: float | None
    ) -> tuple[list[list[tuple[int, int, int, bytes]]], bool]: ...
