"""Generate the Rust tokenizer's Unicode tables from this interpreter.

The Rust tokenizer must be byte-identical to ``vfs.models.lexical.tokenize``,
whose character classes are Python's own (``re``'s ``\\w``, ``str.isupper``,
``str.islower``, ``str.isdigit``, ``str.casefold``). Rather than trust a
third-party Unicode crate to agree with CPython's tables, the classes are
dumped from the interpreter as range tables and a casefold map, so the
Rust side is exact by construction for this interpreter's Unicode version.

    uv run --no-sync python gen_unicode_tables.py > rustbench/src/tables.rs
"""

from __future__ import annotations

import re
import sys
import unicodedata

WORD = re.compile(r"\w")


def ranges(predicate) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            hit = False
        else:
            hit = predicate(chr(cp))
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit_ranges(name: str, rs: list[tuple[int, int]]) -> None:
    print(f"pub static {name}: [(u32, u32); {len(rs)}] = [")
    for lo, hi in rs:
        print(f"    (0x{lo:X}, 0x{hi:X}),")
    print("];")


def main() -> None:
    print(f"// Generated by gen_unicode_tables.py from CPython {sys.version.split()[0]}, unicodedata {unicodedata.unidata_version}.")
    print("// Do not edit: the tables are the interpreter's own character classes.\n")
    emit_ranges("WORD", ranges(lambda ch: WORD.fullmatch(ch) is not None))
    emit_ranges("UPPER", ranges(str.isupper))
    emit_ranges("LOWER", ranges(str.islower))
    emit_ranges("DIGIT", ranges(str.isdigit))
    folds = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        folded = ch.casefold()
        if folded != ch:
            folds.append((cp, folded))
    print(f"pub static CASEFOLD: [(u32, &str); {len(folds)}] = [")
    for cp, folded in folds:
        lit = "".join(f"\\u{{{ord(c):X}}}" for c in folded)
        print(f'    (0x{cp:X}, "{lit}"),')
    print("];")


if __name__ == "__main__":
    main()
